// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEnsajXABIaIR9gr_IQ9N4QCo7kzx0LX0',
    appId: '1:539672090853:web:b90c2e109f359dbf2edc0c',
    messagingSenderId: '539672090853',
    projectId: 'flutter-chat-app-7088b',
    authDomain: 'flutter-chat-app-7088b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7088b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgCdo-dwDnAkHRN_a38gBEbH1VFoUBSHY',
    appId: '1:539672090853:android:383c3e03bdb26fe72edc0c',
    messagingSenderId: '539672090853',
    projectId: 'flutter-chat-app-7088b',
    storageBucket: 'flutter-chat-app-7088b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQEokt9RqWrDfwN-rWaeslHj038sUoes',
    appId: '1:539672090853:ios:5ed9daa041f9f6c42edc0c',
    messagingSenderId: '539672090853',
    projectId: 'flutter-chat-app-7088b',
    storageBucket: 'flutter-chat-app-7088b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMQEokt9RqWrDfwN-rWaeslHj038sUoes',
    appId: '1:539672090853:ios:6ad6deecc8aafdaf2edc0c',
    messagingSenderId: '539672090853',
    projectId: 'flutter-chat-app-7088b',
    storageBucket: 'flutter-chat-app-7088b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
